### ISSUE TITLE
Bun support went away after 0.1.8 update.

### ISSUE THREAD

**Issue by samheart564** [nhristov/astro-compress#472]
After version 0.1.8 added `Updated core module imports to use Node.js node: protocol for fs, path, and buffer`, the integration errors out when using the Bun runtime. Specifically, when trying to compress **IMAGES**. I have not tested this on CSS, JS, and HTML, but it does still compress SVG.

For example, if I do 
`bunx --bun astro build`, it doesn't work and gives a lot of errors, 

but when I do `bunx astro build` it works fine and compresses normally.

In version 0.1.7 (and under), it still worked and compressed normally even when I did `bunx --bun astro build`.

I understand this is a pretty minor issue, but as someone who really enjoys using Bun for everything possible, I would appreciate if Bun support could get added back again. I understand if you decide not to though cause it is really minor.  

![Image](https://github.com/user-attachments/assets/ccd6c02f-2d56-4eee-a780-48e2914ad225)

In addition to this output, I also get an 

`Error: Cannot compress file //dist/_astro/<...filename>` error below it for every file. 

I want to clarify, Astro still builds fine, and the output website still looks fine even after the integration errors out, it's just the integration is no longer compressing the files.

**Comment by NikolaRHristov** [comment]
Hi @samheart564. Thank you for this issue, I notice in the error that it expects `_Map` to be defined before the `export default` in:

https://github.com/PlayForm/Compress/blob/714edf6a03852d0bfdbfdc341d567c01e7dd57d3/Source/Function/Image/Writesharp.ts

We have released a new [`@playform/compress@v0.2.0`](https://github.com/PlayForm/Compress/releases/tag/Compress%2Fv0.2.0) with this specific fix - https://github.com/PlayForm/Compress/blob/Current/Source/Function/Image/Writesharp.ts and others in mind.

Can you give that - https://npmjs.org/@playform/compress a try?

**Comment by therealsamyak** [comment]
> Hi [@samheart564](https://github.com/samheart564). Thank you for this issue, I notice in the error that it expects `_Map` to be defined before the `export default` in:
> 
> [`714edf6`/Source/Function/Image/Writesharp.ts](https://github.com/PlayForm/Compress/blob/714edf6a03852d0bfdbfdc341d567c01e7dd57d3/Source/Function/Image/Writesharp.ts)
> 
> We have released a new [`@playform/compress@v0.2.0`](https://github.com/PlayForm/Compress/releases/tag/Compress%2Fv0.2.0) with this specific fix - [`Current`/Source/Function/Image/Writesharp.ts](https://github.com/PlayForm/Compress/blob/Current/Source/Function/Image/Writesharp.ts?rgh-link-date=2025-06-10T07%3A41%3A49.000Z) and others in mind.
> 
> Can you give that - [npmjs.org/@playform/compress](https://npmjs.org/@playform/compress) a try?

![Image](https://github.com/user-attachments/assets/a7f37659-896d-4956-8d86-4b0f011fbc9a)

Sorry, I am still getting a similar error when using Bun. When I switch back to Node it works fine though. From what I can see it looks like the same type of error but just with a different file now. 🤔

**Comment by NikolaRHristov** [comment]
The error says the `default` is not defined in:

```js
const { default: i } = await import("../../Variable/Image/Mapsharp.js");
var o = async (...[a, { Buffer: t, Input: r }]) => {
	const f = r.split(".").pop();
	if (!f) return;
	const e = typeof i[f] < "u" ? i[f] : typeof a[f] < "u" ? f : !1;
	if (
		e &&
		["avif", "gif", "heif", "jpeg", "png", "raw", "tiff", "webp"].includes(
			e,
		) &&
		typeof a[e] < "u" &&
		a[e] !== !1
	)
		return (
			e in t &&
			(await t[e](
				a[e] !== !0
					? a[e]
					: (await import("../../Variable/Image/sharp.js")).default,
			).toBuffer())
		);
};
export { i as _Map, o as default };
```

which it is.

Could you go into `node_modules/@playform/compress` and paste the contents of: `node_modules/@playform/compress/Target/Function/Image/Writesharp.js`? Maybe try a re-install, install of `node_modules`?

**Comment by NikolaRHristov** [comment]
@samheart564 Also, I found these two issues on the Bun's GitHub - https://github.com/oven-sh/bun/issues/20270, https://github.com/oven-sh/bun/issues/18615. They might be related.

**Comment by samheart564** [comment]
> Could you go into `node_modules/@playform/compress` and paste the contents of: `node_modules/@playform/compress/Target/Function/Image/Writesharp.js`? Maybe try a re-install, install of `node_modules`?

The contents are as follows

```
const{default:i}=await import("../../Variable/Image/Mapsharp.js");var o=async(...[a,{Buffer:t,Input:r}])=>{const f=r.split(".").pop();if(!f)return;const e=typeof i[f]<"u"?i[f]:typeof a[f]<"u"?f:!1;if(e&&["avif","gif","heif","jpeg","png","raw","tiff","webp"].includes(e)&&typeof a[e]<"u"&&a[e]!==!1)return e in t&&await t[e](a[e]!==!0?a[e]:(await import("../../Variable/Image/sharp.js")).default).toBuffer()};export{i as _Map,o as default};
```

I agree it could just be an issue with Bun overall and it's not your (Playform's) fault. As I said earlier, its fine if you don't decide to act based on this issue because it is really minor and affects probably only just me at the end of the day anyways. The workaround (not using Bun for the build command) is an easy fix and functionally doesn't change anything for me.  

Thanks for your help!

**Comment by NikolaRHristov** [comment]
Thanks @samheart564. We'll definitely take a look.
